### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [zardus/preeny#26]
I am a developer with the ArchStrike team, we have been asked to add this to our repo. We think its a fine addition, but its missing two things a license and possibly a git tag. Its much easier for us to add things to the repo, if we can pull from a git tag and add a tool with a proper license.

https://github.com/ArchStrike/ArchStrike/issues/180

**Comment by zardus** [comment]
Sounds cool! I'm polling the other contributors to make sure we all agree on BSD, and will then add it and make a tagged release.

**Comment by zardus** [comment]
Alright, we have a license and a release! The license is BSD, and the release is here: https://github.com/zardus/preeny/releases/tag/0.1

Let me know if there's anything else that should be done!

**Comment by archey** [comment]
Thanks we will pkg it and pull from the tag releases as it updates.

**Comment by archey** [comment]
PKG is built closing this for now, we will open a new issue if needed
