### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zardus** [zardus/preeny#27]
Apparently, I was an idiot and didn't throw in any sort of license. Issue #26 points out that this is required for some Linux distributions, so I guess we should do that.

I'm leaning towards BSD because it'd be easiest, but let's take a poll of the contributors. If there are objections, we'll discuss further.

@crowell, @cao, @justinclift, @bheesham, @ekse, @MiWCryptoCurrency, @ghedo, @mkevac, @ZetaTwo, @technion, as the exhaustive list of esteemed preeny contributors, do any of you have any objections to a BSD license?

**Comment by ekse** [comment]
My only conribution was to fix a typo in the readme but BSD is fine with me  :+1:

**Comment by cao** [comment]
BSD works for me :+1:

**Comment by bheesham** [comment]
No objections. :+1:

**Comment by technion** [comment]
I support BSD license.

**Comment by justinclift** [comment]
Hmmm, BSD license doesn't have patent protection provisions, but it's **probably** not going to matter for this. :smile:

So BSD... yeah why not. 😁

**Comment by ZetaTwo** [comment]
BSD > Copyleft

I support this.

**Comment by mkevac** [comment]
No objections.

**Comment by crowell** [comment]
Bsd is good for me

**Comment by MiWCryptoCurrency** [comment]
BSD ok

**Comment by zardus** [comment]
Okay! I think we have almost everyone, with no objections. I'll go with BSD!
