### ISSUE TITLE
 Protocol not supported 'TCP' with socketpair(AF_UNIX, type, protocol, fds) desock.c:162

### ISSUE THREAD

**Issue by MiWCryptoCurrency** [zardus/preeny#5]
Hello,

I have been trying to follow the instrumentation pattern in using preeny desock.so to redirect AF_INET TCP sockets to stdin/out for use with afl-fuzz.

A guide with nginx has been documented by lolware here https://lolware.net/2015/04/28/nginx-fuzzing.html
With openssl, LD_PRELOAD with desock.so will terminate with a 
preeny socket emulation failed:: Protocol not supported

I think this is because on desock.c:162 
    int r = socketpair(AF_UNIX, type, protocol, fds);
the unix socket for stdin/out is being passed '6' for TCP as per /etc/protocols

When I remove protocol and pass a 0 to socketpair() the TCP socket from openssl is redirected to stdin/out and it functions as expected. 
It doesn't make sense to create an AF_UNIX socket with a protocol of TCP, this isn't supported. 
The protocol variable is also used if the original socket is passed through, in the event not (AF_INET or AF_INET6) so it does need to used.

I believe the desock:162 should be further down, after desock:166
    if (domain != AF_INET && domain != AF_INET6)
check. 

The intercepted function can check for socket interception validity and return out before it needs to instantiate a new socket. It also would prevent creation a socket for invalid (e.g. non-AF_INET) sockets with invalid protocols. I'm not sure where that is being cleaned up either so it might be a memory leak?

Thanks, and I'm really enjoying your code, thank you for releasing it.

**Comment by MiWCryptoCurrency** [comment]
Suggested req here https://github.com/zardus/preeny/pull/6

**Comment by zardus** [comment]
Ah, good call. This is something that I also ran into in a CTF a little while back, actually, but forgot to go back and look at. It's awesome to see it fixed!

Also, you're right about the leak. An FD leak, too. Color me embarrassed :-)

I merged the PR. Thank you for using and improving preeny!

**Comment by thinkycx** [comment]
Hello guys!  Thanks for your code for  the src/desock.c.

I am also reading the source code of src/desock.c now and trying to use it.
I wonder that does the desock.c only supports the binary which support the AF_UNIX domain socket? ( For example, I ran into nginx and found it supports the AF_UNIX domain socket. )

**What will happen if it comes into a binary which only support AF_INET AF_INET6 domain socket?**
Which also means the socket function's domain is not AF_UNIX  in the binary 
I use it and see the log, and the . "Ignoring non-internet socket" will be printed. 
**How can I send the DATA into the binary from the STDIN ?**

Thanks!

**Comment by thinkycx** [comment]
> Hello guys! Thanks for your code for the src/desock.c.
> 
> I am also reading the source code of src/desock.c now and trying to use it.
> I wonder that does the desock.c only supports the binary which support the AF_UNIX domain socket? ( For example, I ran into nginx and found it supports the AF_UNIX domain socket. )
> 
> **What will happen if it comes into a binary which only support AF_INET AF_INET6 domain socket?**
> Which also means the socket function's domain is not AF_UNIX in the binary
> I use it and see the log, and the . "Ignoring non-internet socket" will be printed.
> **How can I send the DATA into the binary from the STDIN ?**
> 
> Thanks!

Sorry that I mistake the source code, the point is that only the AF_INET & AF_INET6 domain socket can be used.
```
	if (domain != AF_INET && domain != AF_INET6)    
	{
		preeny_info("Ignoring non-internet socket.");
		return original_socket(domain, type, protocol);
	}
	
	int r = socketpair(AF_UNIX, type, 0, fds);		
```
