### ISSUE TITLE
Can I compile preeny on an arm-based raspberrypi device?

### ISSUE THREAD

**Issue by buptsseGJ** [zardus/preeny#54]
Hello,
     I want to compile it on my raspberrypi device, but it causes an error which doesn't occur on my X86_64 computer. The gcc is arm-linux-gnueabihf with 6.3.0 version.
The error is as follows:
```
make -C src clean
make[1]: Entering directory '/home/pi/Downloads/protocal/preeny/src'
rm -f *.o
rm -f *.so
make[1]: Leaving directory '/home/pi/Downloads/protocal/preeny/src'
make -C src dist
make[1]: Entering directory '/home/pi/Downloads/protocal/preeny/src'
cc dealarm.c logging.c -o dealarm.so -shared -fPIC  -Wall -DLINUX -ldl
cc setcanary.c logging.c -o setcanary.so -shared -fPIC  -Wall -DLINUX -ldl
setcanary.c: In function ‘preeny_set_canary’:
setcanary.c:26:25: warning: implicit declaration of function ‘TONUMBER’ [-Wimplicit-function-declaration]
  uintptr_t new_canary = TONUMBER(new_canary_str, NULL, 0);
                         ^~~~~~~~
setcanary.c:30:3: error: expected ‘:’ or ‘)’ before ‘INSN_LOAD’
   INSN_LOAD
   ^~~~~~~~~
Makefile:69: recipe for target 'setcanary.so' failed
make[1]: *** [setcanary.so] Error 1
make[1]: Leaving directory '/home/pi/Downloads/protocal/preeny/src'
Makefile:6: recipe for target 'dist' failed
make: *** [dist] Error 2
```
Look forward for your reply. Thank you!

**Comment by sudhackar** [comment]
We only support x86 and x86-64 for now.

https://github.com/zardus/preeny/blob/5d544d63e7ab363c7c465c6fd36f86b2bb41f85c/src/setcanary.c#L5

https://github.com/zardus/preeny/blob/5d544d63e7ab363c7c465c6fd36f86b2bb41f85c/src/setcanary.c#L11

You're welcome to PR.

**Comment by zardus** [comment]
Some of the preloads won't compile on some architectures or platforms, but
you can use make -i to just skip them.

**Comment by sudhackar** [comment]
@zardus I have implemented canary read/write for arm. Are you planning on supporting arm?

**Comment by zardus** [comment]
Yeah! Like I said, we should support every arch in general, just some
preloads are harder to support than others. Could you contribute your arm
support?

**Comment by sudhackar** [comment]
For setcanary its a little tricky as the page where `__stack_chk_guard` is mapped only `r` in the latest version I tested with on raspberry pi. Need to map it `rw`, write cookie and then map it to `r` back. If that's ok, I'll add a PR for that. Seems too intrusive to me.

**Comment by zardus** [comment]
I think intrusive is better than unsupported :-)

Thanks for sorting this out!
