### ISSUE TITLE
Errors with desock.so and desock.dup

### ISSUE THREAD

**Issue by powerthe900** [zardus/preeny#74]
I am trying to use preeny to make lighttpd recieve http requests from stdin. Hence, I used desock.so and desock_dup,so. When I use desock.so, I get this error: setsockopt(TCP_NODELAY) failed: Operation not supported. When I use desock_dup.so, I get this error: setting default fds failed: Success.  

Have you guys occurred this error before? How would I solve this?

**Comment by zardus** [comment]
It looks like lighttpd is treating the socketpair that preeny replaced the network connection with as a network socket, and is trying to set socket options on it. The way to handle this for desock is to add some handling (probably just `return 0`) for setsockopts in the module. Not sure what's happening with desock_dup, but I'm guessing a similar root cause (treating the FD as a socket).

**Comment by powerthe900** [comment]
This is the c code that throws the error `srv->cur_fds = srv_socket->fd;

	if (fdevent_set_so_reuseaddr(srv_socket->fd, 1) < 0) {
		log_error_write(srv, __FILE__, __LINE__, "ss", "setsockopt(SO_REUSEADDR) failed:", strerror(errno));
		return -1;
	}

	if (family != AF_UNIX) {
		if (fdevent_set_tcp_nodelay(srv_socket->fd, 1) < 0) {
			log_error_write(srv, __FILE__, __LINE__, "ss", "setsockopt(TCP_NODELAY) failed:", strerror(errno));
			return -1;
		}
	}

	if (-1 != stdin_fd) { } else
	if (0 != bind(srv_socket->fd, (struct sockaddr *) &(srv_socket->addr), addr_len)) {
		log_error_write(srv, __FILE__, __LINE__, "sss",
				"can't bind to socket:", host, strerror(errno));
		return -1;
	}

	if (-1 != stdin_fd) { } else
	if (AF_UNIX == family && !buffer_string_is_empty(s->socket_perms)) {
		mode_t m = 0;
		for (char *str = s->socket_perms->ptr; *str; ++str) {
			m <<= 3;
			m |= (*str - '0');
		}
		if (0 != m && -1 == chmod(host, m)) {
			log_error_write(srv, __FILE__, __LINE__, "sssbss", "chmod(\"", host, "\", ", s->socket_perms, "):", strerror(errno));
		}
	}

	if (-1 != stdin_fd) { } else
	if (-1 == listen(srv_socket->fd, s->listen_backlog)) {
		log_error_write(srv, __FILE__, __LINE__, "ss", "listen failed: ", strerror(errno));
		return -1;
	}`
The specific part that causes the error is if (family != AF_UNIX) { .... Hence, I deleted that if statement. For desock_dup.so, the error is thrown here `/* close stdin and stdout, as they are not needed */
	{
		struct stat st;
		int devnull;
		int errfd;
		do {
			/* coverity[overwrite_var : FALSE] */
			devnull = fdevent_open_devnull();
		      #ifdef __COVERITY__
			__coverity_escape__(devnull);
		      #endif
		} while (-1 != devnull && devnull <= STDERR_FILENO);
		if (-1 == devnull) {
			log_error_write(srv, __FILE__, __LINE__, "ss",
					"opening /dev/null failed:", strerror(errno));
			return -1;
		}
		errfd = (0 == fstat(STDERR_FILENO, &st)) ? -1 : devnull;
		if (0 != fdevent_set_stdin_stdout_stderr(devnull, devnull, errfd)) {
			log_error_write(srv, __FILE__, __LINE__, "ss",
					"setting default fds failed:", strerror(errno));
		      #ifdef FD_CLOEXEC
			if (-1 != errfd) close(errfd);
			if (devnull != errfd) close(devnull);
		      #endif
			return -1;
		}
	      #ifdef FD_CLOEXEC
		if (-1 != errfd) close(errfd);
		if (devnull != errfd) close(devnull);
	      #endif
	}

	if (0 != config_set_defaults(srv)) {
		log_error_write(srv, __FILE__, __LINE__, "s",
				"setting default values failed");
		return -1;
	}`
As you can see, they are trying to disable stdin and stdout, so I deleted this entire portion of the code. Then I successfully compiled the binary, and I sent an invalid request through stdin. The request threw a 501 error through stdout and everything worked fine. However, when I tried using a valid request with stdin, there was no stdout. I checked my error log and I got a connection reset by peer error. This linked me with another file. 
`	cnt = fdevent_accept_listenfd(srv_socket->fd, (struct sockaddr *) &cnt_addr, &cnt_len);
	if (-1 == cnt) {
		switch (errno) {
		case EAGAIN:
#if EWOULDBLOCK != EAGAIN
		case EWOULDBLOCK:
#endif
		case EINTR:
			/* we were stopped _before_ we had a connection */
		case ECONNABORTED: /* this is a FreeBSD thingy */
			/* we were stopped _after_ we had a connection */
			break;
		case EMFILE:
			/* out of fds */
			break;
		default:
			log_error_write(srv, __FILE__, __LINE__, "ssd", "accept failed:", strerror(errno), errno);
		}
		return NULL;
	} else {
		if (sock_addr_get_family(&cnt_addr) != AF_UNIX) {
			network_accept_tcp_nagle_disable(cnt);
		}
		return connection_accepted(srv, srv_socket, &cnt_addr, cnt);
	}
}


/* 0: everything ok, -1: error, -2: con closed */
static int connection_read_cq(server *srv, connection *con, chunkqueue *cq, off_t max_bytes) {
	ssize_t len;
	char *mem = NULL;
	size_t mem_len = 0;
	force_assert(cq == con->read_queue);       /*(code transform assumption; minimize diff)*/
	force_assert(max_bytes == MAX_READ_LIMIT); /*(code transform assumption; minimize diff)*/

	/* check avail data to read and obtain memory into which to read
	 * fill previous chunk if it has sufficient space
	 * (use mem_len=0 to obtain large buffer at least half of chunk_buf_sz)
	 */
	{
		int frd;
		if (0 == fdevent_ioctl_fionread(con->fd, S_IFSOCK, &frd)) {
			mem_len = (frd < MAX_READ_LIMIT) ? (size_t)frd : MAX_READ_LIMIT;
		}
	}`
The specific error in the error log is at log_errror_write. Also, to send the previous requests through stdin I used desock.so. 

How would I fix this error and make valid requests work? Or is my method of patching wrong or is there an easier option?

**Comment by powerthe900** [comment]
Sorry if the source code part looks wierd.

**Comment by powerthe900** [comment]
The return zero method did not work.

**Comment by powerthe900** [comment]
The binary has a one shot mode that process single (one) request on stdin socket, then exit. When I use desock.so and pass a normal http request through stdin, it says that -1 is not a socket. How would I bypass this?

**Comment by powerthe900** [comment]
Ive got it to work

**Comment by zardus** [comment]
What was the solution in the end?

https://xkcd.com/979/ :-)

**Comment by gstrauss** [comment]
FYI: the next version of lighttpd 1.4.56 additionally supports a special case of `lighttpd -1` (one-shot mode) with pipes on stdin and stdout, e.g. for use with a `netcat` listener.  The current `lighttpd -1` expects a socket on stdin.

**Comment by powerthe900** [comment]
The solution was that they closed stdin in the program. You would just have to delete that section in the code and desock worked.
