### ISSUE TITLE
[PATCH][SUGGESTION] Would you like to add setstdin to this set of libs 

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [zardus/preeny#75]
Hi!
I've written a small lib that I need to substitute an STDIN I need via LD_PRELOAD.

I guess it worth adding to the preeny library set.

If you like it, I can file it as a pull request.

[setstdin.tar.gz](https://github.com/zardus/preeny/files/5355672/setstdin.tar.gz)

setstdin.c is the library to include.
out.c is a main file to test it.

You should set PREENY_STDIN or PREENY_STDIN_FILENAME environment variables to set your own data to be substituted as STDIN

**Comment by vanhauser-thc** [comment]
I would recommend to send a pull request instead of a .tar.gz
(read on the Internet for how to do it, its easy, fork, make your changes, then click "create pull request" in your fork)

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I know how to make pull request. I decided to check, if you like the idea of such lib first. Before doing job with editing readme, changing Makefile etc...

BTW I've figured out that I had to add fgetc to this lib to properly suit my purposes, so I guess here I should also add fread too. So I will provide improved version later, when I do all of it.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Actually it is already commit. 

Commits: e317826b59f177b57207d0d85e3fb03262559b61 1a81fd5e5bf4479f1a469cddf6de1899ab290774 c9f5e6e37557f29832daf0391bdb05f3e47ff405
